// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && ebpf

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBlockLatency returns the embedded CollectionSpec for blockLatency.
func loadBlockLatency() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BlockLatencyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load blockLatency: %w", err)
	}

	return spec, err
}

// loadBlockLatencyObjects loads blockLatency and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*blockLatencyObjects
//	*blockLatencyPrograms
//	*blockLatencyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBlockLatencyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBlockLatency()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// blockLatencySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockLatencySpecs struct {
	blockLatencyProgramSpecs
	blockLatencyMapSpecs
}

// blockLatencySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockLatencyProgramSpecs struct {
	TraceRqComplete *ebpf.ProgramSpec `ebpf:"trace_rq_complete"`
	TraceRqIssue    *ebpf.ProgramSpec `ebpf:"trace_rq_issue"`
}

// blockLatencyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockLatencyMapSpecs struct {
	IoLatencyHist *ebpf.MapSpec `ebpf:"io_latency_hist"`
	StartTimes    *ebpf.MapSpec `ebpf:"start_times"`
}

// blockLatencyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBlockLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockLatencyObjects struct {
	blockLatencyPrograms
	blockLatencyMaps
}

func (o *blockLatencyObjects) Close() error {
	return _BlockLatencyClose(
		&o.blockLatencyPrograms,
		&o.blockLatencyMaps,
	)
}

// blockLatencyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBlockLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockLatencyMaps struct {
	IoLatencyHist *ebpf.Map `ebpf:"io_latency_hist"`
	StartTimes    *ebpf.Map `ebpf:"start_times"`
}

func (m *blockLatencyMaps) Close() error {
	return _BlockLatencyClose(
		m.IoLatencyHist,
		m.StartTimes,
	)
}

// blockLatencyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBlockLatencyObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockLatencyPrograms struct {
	TraceRqComplete *ebpf.Program `ebpf:"trace_rq_complete"`
	TraceRqIssue    *ebpf.Program `ebpf:"trace_rq_issue"`
}

func (p *blockLatencyPrograms) Close() error {
	return _BlockLatencyClose(
		p.TraceRqComplete,
		p.TraceRqIssue,
	)
}

func _BlockLatencyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed blocklatency_bpfeb.o
var _BlockLatencyBytes []byte
