//go:build linux && ebpf

package ebpf

import (
	"fmt"
	"os"
	"strings"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
)

const histBuckets = 24

// Collector loads and manages the block latency BPF programs.
// It must be created with NewCollector and closed with Close when done.
type Collector struct {
	objs  blockLatencyObjects
	links []link.Link
}

// NewCollector loads the BPF programs into the kernel, attaches them to the
// block_rq_issue and block_rq_complete tracepoints, and returns a Collector
// ready to call ReadHistogram on.
//
// Requires CAP_BPF (Linux 5.8+) or CAP_SYS_ADMIN. The process must be
// running as root or with the relevant capability; sysmon will print a clear
// error if not.
func NewCollector() (*Collector, error) {
	// Check kernel version / BTF availability early to give a useful message.
	if _, err := os.Stat("/sys/kernel/btf/vmlinux"); err != nil {
		return nil, fmt.Errorf(
			"BTF not available at /sys/kernel/btf/vmlinux — requires Linux 5.8+ with CONFIG_DEBUG_INFO_BTF=y: %w", err)
	}

	c := &Collector{}

	// loadBlockLatencyObjects is generated by bpf2go; it loads the
	// embedded BPF bytecode into the kernel and returns typed handles
	// to the programs and maps.
	if err := loadBlockLatencyObjects(&c.objs, nil); err != nil {
		return nil, fmt.Errorf("loading BPF objects: %w", err)
	}

	// Attach to the block_rq_issue tracepoint.
	issueLink, err := link.Tracepoint("block", "block_rq_issue", c.objs.TraceRqIssue, nil)
	if err != nil {
		c.objs.Close()
		return nil, fmt.Errorf("attaching block_rq_issue tracepoint: %w", err)
	}
	c.links = append(c.links, issueLink)

	// Attach to the block_rq_complete tracepoint.
	completeLink, err := link.Tracepoint("block", "block_rq_complete", c.objs.TraceRqComplete, nil)
	if err != nil {
		for _, l := range c.links {
			l.Close()
		}
		c.objs.Close()
		return nil, fmt.Errorf("attaching block_rq_complete tracepoint: %w", err)
	}
	c.links = append(c.links, completeLink)

	return c, nil
}

// LatencyBucket holds the count of I/O requests in a latency range.
type LatencyBucket struct {
	Label string // human-readable range, e.g. "32–64 µs"
	Count uint64
}

// ReadHistogram reads the current I/O latency histogram from the BPF map.
// It returns one LatencyBucket per power-of-2 range; buckets with a count
// of 0 are included so the caller can render a full distribution.
//
// The histogram is cumulative since the Collector was created. Call
// ResetHistogram if you need a per-interval snapshot.
func (c *Collector) ReadHistogram() ([]LatencyBucket, error) {
	buckets := make([]LatencyBucket, histBuckets)

	for i := uint32(0); i < histBuckets; i++ {
		var count uint64
		if err := c.objs.IoLatencyHist.Lookup(i, &count); err != nil {
			// A lookup miss on a zero-initialised array map shouldn't happen,
			// but treat it as 0 rather than failing the whole read.
			if !isNotFound(err) {
				return nil, fmt.Errorf("reading histogram bucket %d: %w", i, err)
			}
		}
		buckets[i] = LatencyBucket{
			Label: bucketLabel(i),
			Count: count,
		}
	}

	return buckets, nil
}

// ResetHistogram zeroes all histogram buckets. Useful for per-interval
// reporting rather than cumulative totals.
func (c *Collector) ResetHistogram() error {
	zero := uint64(0)
	for i := uint32(0); i < histBuckets; i++ {
		if err := c.objs.IoLatencyHist.Put(i, &zero); err != nil {
			return fmt.Errorf("resetting histogram bucket %d: %w", i, err)
		}
	}
	return nil
}

// Close detaches the tracepoints and unloads the BPF programs from the
// kernel. Always call this when the Collector is no longer needed.
func (c *Collector) Close() {
	for _, l := range c.links {
		l.Close()
	}
	c.objs.Close()
}

// RenderASCII returns a simple ASCII histogram string suitable for a
// terminal display, filtering out empty buckets for readability.
func RenderASCII(buckets []LatencyBucket) string {
	var total uint64
	var maxCount uint64
	for _, b := range buckets {
		total += b.Count
		if b.Count > maxCount {
			maxCount = b.Count
		}
	}
	if total == 0 {
		return "  (no I/O recorded yet)\n"
	}

	const barWidth = 30
	var sb strings.Builder
	for _, b := range buckets {
		if b.Count == 0 {
			continue
		}
		filled := int(float64(b.Count) / float64(maxCount) * barWidth)
		pct := float64(b.Count) / float64(total) * 100
		fmt.Fprintf(&sb, "  %-12s [%s%s] %6d  (%4.1f%%)\n",
			b.Label,
			strings.Repeat("█", filled),
			strings.Repeat("─", barWidth-filled),
			b.Count,
			pct,
		)
	}
	return sb.String()
}

// bucketLabel returns a human-readable label for histogram bucket i.
// Bucket 0 = <1 µs, bucket 1 = 1–2 µs, bucket 2 = 2–4 µs, etc.
func bucketLabel(i uint32) string {
	if i == 0 {
		return "<1 µs"
	}
	lo := uint64(1) << (i - 1)
	hi := lo << 1
	return fmt.Sprintf("%d–%d µs", lo, hi)
}

func isNotFound(err error) bool {
	return err != nil && strings.Contains(err.Error(), ebpf.ErrKeyNotExist.Error())
}
